### ISSUE TITLE
Fiyat girilmemiş ürünlerin sayfası buglanıyor

### ISSUE THREAD

**Issue by Ryo-Pegasus** [malionde/iyzicoTaksit#1]
hocam merhabalar elinize sağlık çok güzel plugin olmuş. saat gibi çalışıyor. fakat eğer ürün fiyatı girilmemiş katalog varyasyonlu ürünlerde front end 'e sayfanın boş (blank) yüklenmesine neden oluyor ürün fiyatını çekemediği için sanırım. acaba fiyat girilmemiş ürünlerde pluginin echo 'lanmasını nasıl engelleyebiliriz?

**Comment by malionde** [comment]
Merhabalar, 
13. satırda  `get_display_price()` methodu ile ilgili ürünün fiyatını çekerken bir sorun yaşıyorsunuz gibi. İsterseniz aşağıdaki şekilde bir kontrol ekleyerek değer gelmemiş ürünlere 0 basar ve İyzico tarafına o şekilde bir istekte bulunabilirsiniz.
`isset($regular_price) ? $regular_price : 0;`

44. Satırda request'in setPrice methoduna bu şekilde parametre gönderebilirsiniz. 
`$request->setPrice("isset($regular_price) ? $regular_price : 0");`

**Comment by Ryo-Pegasus** [comment]
`add_filter('woocommerce_product_tabs', 'woo_new_product_tab');
function woo_new_product_tab($tabs)
{

    // Adds the new tab
    $tabs['test_tab'] = array(
        'title' => __('Taksit Seçenekleri', 'woocommerce'),
        'priority' => 50,
        'callback' => 'woo_new_product_tab_content'
    );
    return $tabs;
}

function woo_new_product_tab_content()
{
    //Include external resources 
    require_once('config.php');
    require_once ('style.css');
   
    //Get product price
    global $product;
    $regular_price = esc_attr( $product->get_display_price() );

    // The new tab content
    echo '<p style="font-size:11px;">*Taksit sayısı bankanızın yetkilendirmesine bağlı olarak değişiklik gösterebilir. En doğru oran ve sonucu ödeme tamamlama ekranında net bir şekilde görebilirsiniz.</p>';
    //echo 'Ürünün Fiyatı '.$regular_price.' TL dir.';
    
    # create request class
    $request = new \Iyzipay\Request\RetrieveInstallmentInfoRequest();
    $request->setLocale(\Iyzipay\Model\Locale::TR);
    $request->setConversationId(uniqid());
    //$request->setBinNumber("554960");
    $request->setPrice("isset($regular_price) ? $regular_price : 0");
    
    # make request`

dediğiniz gibi yaptım. fakat bu sefer fiyat olan olmayan tüm ürünlerin sayfasını yüklerken hata verdi

**Comment by malionde** [comment]
Tekrardan merhabalar dostum.

İnan yardımcı olmayı çok isterim fakat şu anda iş yoğunluğum hat safhada ve
PHP aktif olarak kullandığım bir dil değil. Bir iş için yapmıştım ve belki
birilerine yardımcı olabilirim diye github'a atmıştım. Umarım seninde işine
yaramıştır. Eğer bir geliştirme yaparsan contribute yapabilirsin :)

İyi çalışmalar dilerim.
Mehmet Ali Önde

Yigit OCAK ***@***.***>, 18 Haz 2021 Cum, 15:58 tarihinde
şunu yazdı:
